// Code generated by MockGen. DO NOT EDIT.
// Source: sigs.k8s.io/controller-runtime/pkg/controller (interfaces: Controller)
//
// Generated by this command:
//
//	mockgen -destination=./tests/mocks/controller.go -package=mocks sigs.k8s.io/controller-runtime/pkg/controller Controller
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	logr "github.com/go-logr/logr"
	gomock "go.uber.org/mock/gomock"
	reconcile "sigs.k8s.io/controller-runtime/pkg/reconcile"
	source "sigs.k8s.io/controller-runtime/pkg/source"
)

// MockController is a mock of Controller interface.
type MockController[request comparable] struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder[request]
	isgomock struct{}
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder[request comparable] struct {
	mock *MockController[request]
}

// NewMockController creates a new mock instance.
func NewMockController[request comparable](ctrl *gomock.Controller) *MockController[request] {
	mock := &MockController[request]{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder[request]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController[request]) EXPECT() *MockControllerMockRecorder[request] {
	return m.recorder
}

// GetLogger mocks base method.
func (m *MockController[request]) GetLogger() logr.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogger")
	ret0, _ := ret[0].(logr.Logger)
	return ret0
}

// GetLogger indicates an expected call of GetLogger.
func (mr *MockControllerMockRecorder[request]) GetLogger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogger", reflect.TypeOf((*MockController[request])(nil).GetLogger))
}

// Reconcile mocks base method.
func (m *MockController[request]) Reconcile(arg0 context.Context, arg1 reconcile.Request) (reconcile.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", arg0, arg1)
	ret0, _ := ret[0].(reconcile.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockControllerMockRecorder[request]) Reconcile(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockController[request])(nil).Reconcile), arg0, arg1)
}

// Start mocks base method.
func (m *MockController[request]) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockControllerMockRecorder[request]) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockController[request])(nil).Start), ctx)
}

// Watch mocks base method.
func (m *MockController[request]) Watch(src source.TypedSource[reconcile.Request]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", src)
	ret0, _ := ret[0].(error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockControllerMockRecorder[request]) Watch(src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockController[request])(nil).Watch), src)
}
