// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SneaksAndData/arcane-operator/services/controllers/stream (interfaces: JobBuilder)
//
// Generated by this command:
//
//	mockgen -destination=./tests/mocks/job_builder.go -package=mocks github.com/SneaksAndData/arcane-operator/services/controllers/stream JobBuilder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	job "github.com/SneaksAndData/arcane-operator/services/job"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/batch/v1"
	types "k8s.io/apimachinery/pkg/types"
)

// MockJobBuilder is a mock of JobBuilder interface.
type MockJobBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockJobBuilderMockRecorder
	isgomock struct{}
}

// MockJobBuilderMockRecorder is the mock recorder for MockJobBuilder.
type MockJobBuilderMockRecorder struct {
	mock *MockJobBuilder
}

// NewMockJobBuilder creates a new mock instance.
func NewMockJobBuilder(ctrl *gomock.Controller) *MockJobBuilder {
	mock := &MockJobBuilder{ctrl: ctrl}
	mock.recorder = &MockJobBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobBuilder) EXPECT() *MockJobBuilderMockRecorder {
	return m.recorder
}

// BuildJob mocks base method.
func (m *MockJobBuilder) BuildJob(ctx context.Context, templateName types.NamespacedName, configurator job.Configurator) (*v1.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildJob", ctx, templateName, configurator)
	ret0, _ := ret[0].(*v1.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildJob indicates an expected call of BuildJob.
func (mr *MockJobBuilderMockRecorder) BuildJob(ctx, templateName, configurator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildJob", reflect.TypeOf((*MockJobBuilder)(nil).BuildJob), ctx, templateName, configurator)
}
