// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SneaksAndData/arcane-operator/services/controllers/stream_class (interfaces: StreamClassMetricsReporter)
//
// Generated by this command:
//
//	mockgen -destination=./tests/mocks/metrics_reporter.go -package=mocks github.com/SneaksAndData/arcane-operator/services/controllers/stream_class StreamClassMetricsReporter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStreamClassMetricsReporter is a mock of StreamClassMetricsReporter interface.
type MockStreamClassMetricsReporter struct {
	ctrl     *gomock.Controller
	recorder *MockStreamClassMetricsReporterMockRecorder
	isgomock struct{}
}

// MockStreamClassMetricsReporterMockRecorder is the mock recorder for MockStreamClassMetricsReporter.
type MockStreamClassMetricsReporterMockRecorder struct {
	mock *MockStreamClassMetricsReporter
}

// NewMockStreamClassMetricsReporter creates a new mock instance.
func NewMockStreamClassMetricsReporter(ctrl *gomock.Controller) *MockStreamClassMetricsReporter {
	mock := &MockStreamClassMetricsReporter{ctrl: ctrl}
	mock.recorder = &MockStreamClassMetricsReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamClassMetricsReporter) EXPECT() *MockStreamClassMetricsReporterMockRecorder {
	return m.recorder
}

// AddStreamClass mocks base method.
func (m *MockStreamClassMetricsReporter) AddStreamClass(kind, metricName string, tags map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddStreamClass", kind, metricName, tags)
}

// AddStreamClass indicates an expected call of AddStreamClass.
func (mr *MockStreamClassMetricsReporterMockRecorder) AddStreamClass(kind, metricName, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStreamClass", reflect.TypeOf((*MockStreamClassMetricsReporter)(nil).AddStreamClass), kind, metricName, tags)
}

// RemoveStreamClass mocks base method.
func (m *MockStreamClassMetricsReporter) RemoveStreamClass(kind string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveStreamClass", kind)
}

// RemoveStreamClass indicates an expected call of RemoveStreamClass.
func (mr *MockStreamClassMetricsReporterMockRecorder) RemoveStreamClass(kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveStreamClass", reflect.TypeOf((*MockStreamClassMetricsReporter)(nil).RemoveStreamClass), kind)
}
