// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SneaksAndData/arcane-operator/services/controllers/stream_class (interfaces: StreamControllerFactory)
//
// Generated by this command:
//
//	mockgen -destination=./tests/mocks/stream_controller_factory.go -package=mocks github.com/SneaksAndData/arcane-operator/services/controllers/stream_class StreamControllerFactory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	v1 "github.com/SneaksAndData/arcane-operator/pkg/apis/streaming/v1"
	stream_class "github.com/SneaksAndData/arcane-operator/services/controllers/stream_class"
	gomock "go.uber.org/mock/gomock"
)

// MockStreamControllerFactory is a mock of StreamControllerFactory interface.
type MockStreamControllerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockStreamControllerFactoryMockRecorder
	isgomock struct{}
}

// MockStreamControllerFactoryMockRecorder is the mock recorder for MockStreamControllerFactory.
type MockStreamControllerFactoryMockRecorder struct {
	mock *MockStreamControllerFactory
}

// NewMockStreamControllerFactory creates a new mock instance.
func NewMockStreamControllerFactory(ctrl *gomock.Controller) *MockStreamControllerFactory {
	mock := &MockStreamControllerFactory{ctrl: ctrl}
	mock.recorder = &MockStreamControllerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamControllerFactory) EXPECT() *MockStreamControllerFactoryMockRecorder {
	return m.recorder
}

// CreateStreamOperator mocks base method.
func (m *MockStreamControllerFactory) CreateStreamOperator(arg0 *v1.StreamClass) (stream_class.StreamControllerHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStreamOperator", arg0)
	ret0, _ := ret[0].(stream_class.StreamControllerHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStreamOperator indicates an expected call of CreateStreamOperator.
func (mr *MockStreamControllerFactoryMockRecorder) CreateStreamOperator(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStreamOperator", reflect.TypeOf((*MockStreamControllerFactory)(nil).CreateStreamOperator), arg0)
}
