// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SneaksAndData/arcane-operator/services/controllers/stream (interfaces: JobManager,StreamDefinition,StreamEvent,StreamManager,StreamRepository,BackfillRequestRepository)
//
// Generated by this command:
//
//	mockgen -destination=./tests/mocks/stream_mocks.go -package=mocks github.com/SneaksAndData/arcane-operator/services/controllers/stream JobManager,StreamDefinition,StreamEvent,StreamManager,StreamRepository,BackfillRequestRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	stream "github.com/SneaksAndData/arcane-operator/services/controllers/stream"
	gomock "go.uber.org/mock/gomock"
)

// MockJobManager is a mock of JobManager interface.
type MockJobManager struct {
	ctrl     *gomock.Controller
	recorder *MockJobManagerMockRecorder
	isgomock struct{}
}

// MockJobManagerMockRecorder is the mock recorder for MockJobManager.
type MockJobManagerMockRecorder struct {
	mock *MockJobManager
}

// NewMockJobManager creates a new mock instance.
func NewMockJobManager(ctrl *gomock.Controller) *MockJobManager {
	mock := &MockJobManager{ctrl: ctrl}
	mock.recorder = &MockJobManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobManager) EXPECT() *MockJobManagerMockRecorder {
	return m.recorder
}

// EnsureStopped mocks base method.
func (m *MockJobManager) EnsureStopped(id stream.StreamIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureStopped", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureStopped indicates an expected call of EnsureStopped.
func (mr *MockJobManagerMockRecorder) EnsureStopped(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureStopped", reflect.TypeOf((*MockJobManager)(nil).EnsureStopped), id)
}

// StartBackfill mocks base method.
func (m *MockJobManager) StartBackfill(definition stream.StreamDefinition) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartBackfill", definition)
}

// StartBackfill indicates an expected call of StartBackfill.
func (mr *MockJobManagerMockRecorder) StartBackfill(definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartBackfill", reflect.TypeOf((*MockJobManager)(nil).StartBackfill), definition)
}

// StartJob mocks base method.
func (m *MockJobManager) StartJob(definition stream.StreamDefinition) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartJob", definition)
}

// StartJob indicates an expected call of StartJob.
func (mr *MockJobManagerMockRecorder) StartJob(definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartJob", reflect.TypeOf((*MockJobManager)(nil).StartJob), definition)
}

// MockStreamDefinition is a mock of StreamDefinition interface.
type MockStreamDefinition struct {
	ctrl     *gomock.Controller
	recorder *MockStreamDefinitionMockRecorder
	isgomock struct{}
}

// MockStreamDefinitionMockRecorder is the mock recorder for MockStreamDefinition.
type MockStreamDefinitionMockRecorder struct {
	mock *MockStreamDefinition
}

// NewMockStreamDefinition creates a new mock instance.
func NewMockStreamDefinition(ctrl *gomock.Controller) *MockStreamDefinition {
	mock := &MockStreamDefinition{ctrl: ctrl}
	mock.recorder = &MockStreamDefinitionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamDefinition) EXPECT() *MockStreamDefinitionMockRecorder {
	return m.recorder
}

// GetConfigurationChecksum mocks base method.
func (m *MockStreamDefinition) GetConfigurationChecksum() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigurationChecksum")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetConfigurationChecksum indicates an expected call of GetConfigurationChecksum.
func (mr *MockStreamDefinitionMockRecorder) GetConfigurationChecksum() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigurationChecksum", reflect.TypeOf((*MockStreamDefinition)(nil).GetConfigurationChecksum))
}

// MockStreamEvent is a mock of StreamEvent interface.
type MockStreamEvent struct {
	ctrl     *gomock.Controller
	recorder *MockStreamEventMockRecorder
	isgomock struct{}
}

// MockStreamEventMockRecorder is the mock recorder for MockStreamEvent.
type MockStreamEventMockRecorder struct {
	mock *MockStreamEvent
}

// NewMockStreamEvent creates a new mock instance.
func NewMockStreamEvent(ctrl *gomock.Controller) *MockStreamEvent {
	mock := &MockStreamEvent{ctrl: ctrl}
	mock.recorder = &MockStreamEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamEvent) EXPECT() *MockStreamEventMockRecorder {
	return m.recorder
}

// BackfillRequested mocks base method.
func (m *MockStreamEvent) BackfillRequested() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackfillRequested")
	ret0, _ := ret[0].(bool)
	return ret0
}

// BackfillRequested indicates an expected call of BackfillRequested.
func (mr *MockStreamEventMockRecorder) BackfillRequested() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackfillRequested", reflect.TypeOf((*MockStreamEvent)(nil).BackfillRequested))
}

// ClassName mocks base method.
func (m *MockStreamEvent) ClassName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClassName")
	ret0, _ := ret[0].(string)
	return ret0
}

// ClassName indicates an expected call of ClassName.
func (mr *MockStreamEventMockRecorder) ClassName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClassName", reflect.TypeOf((*MockStreamEvent)(nil).ClassName))
}

// ConfigurationChecksum mocks base method.
func (m *MockStreamEvent) ConfigurationChecksum() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigurationChecksum")
	ret0, _ := ret[0].(string)
	return ret0
}

// ConfigurationChecksum indicates an expected call of ConfigurationChecksum.
func (mr *MockStreamEventMockRecorder) ConfigurationChecksum() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigurationChecksum", reflect.TypeOf((*MockStreamEvent)(nil).ConfigurationChecksum))
}

// CrashLoopDetected mocks base method.
func (m *MockStreamEvent) CrashLoopDetected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CrashLoopDetected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CrashLoopDetected indicates an expected call of CrashLoopDetected.
func (mr *MockStreamEventMockRecorder) CrashLoopDetected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CrashLoopDetected", reflect.TypeOf((*MockStreamEvent)(nil).CrashLoopDetected))
}

// StreamId mocks base method.
func (m *MockStreamEvent) StreamId() stream.StreamIdentity {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamId")
	ret0, _ := ret[0].(stream.StreamIdentity)
	return ret0
}

// StreamId indicates an expected call of StreamId.
func (mr *MockStreamEventMockRecorder) StreamId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamId", reflect.TypeOf((*MockStreamEvent)(nil).StreamId))
}

// StreamNameSpace mocks base method.
func (m *MockStreamEvent) StreamNameSpace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamNameSpace")
	ret0, _ := ret[0].(string)
	return ret0
}

// StreamNameSpace indicates an expected call of StreamNameSpace.
func (mr *MockStreamEventMockRecorder) StreamNameSpace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamNameSpace", reflect.TypeOf((*MockStreamEvent)(nil).StreamNameSpace))
}

// Suspended mocks base method.
func (m *MockStreamEvent) Suspended() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Suspended")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Suspended indicates an expected call of Suspended.
func (mr *MockStreamEventMockRecorder) Suspended() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Suspended", reflect.TypeOf((*MockStreamEvent)(nil).Suspended))
}

// Type mocks base method.
func (m *MockStreamEvent) Type() stream.EventType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(stream.EventType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockStreamEventMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockStreamEvent)(nil).Type))
}

// MockStreamManager is a mock of StreamManager interface.
type MockStreamManager struct {
	ctrl     *gomock.Controller
	recorder *MockStreamManagerMockRecorder
	isgomock struct{}
}

// MockStreamManagerMockRecorder is the mock recorder for MockStreamManager.
type MockStreamManagerMockRecorder struct {
	mock *MockStreamManager
}

// NewMockStreamManager creates a new mock instance.
func NewMockStreamManager(ctrl *gomock.Controller) *MockStreamManager {
	mock := &MockStreamManager{ctrl: ctrl}
	mock.recorder = &MockStreamManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamManager) EXPECT() *MockStreamManagerMockRecorder {
	return m.recorder
}

// SetFailed mocks base method.
func (m *MockStreamManager) SetFailed(element stream.StreamEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFailed", element)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFailed indicates an expected call of SetFailed.
func (mr *MockStreamManagerMockRecorder) SetFailed(element any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFailed", reflect.TypeOf((*MockStreamManager)(nil).SetFailed), element)
}

// SetOperatorError mocks base method.
func (m *MockStreamManager) SetOperatorError(element stream.StreamEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOperatorError", element)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOperatorError indicates an expected call of SetOperatorError.
func (mr *MockStreamManagerMockRecorder) SetOperatorError(element any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOperatorError", reflect.TypeOf((*MockStreamManager)(nil).SetOperatorError), element)
}

// MockStreamRepository is a mock of StreamRepository interface.
type MockStreamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStreamRepositoryMockRecorder
	isgomock struct{}
}

// MockStreamRepositoryMockRecorder is the mock recorder for MockStreamRepository.
type MockStreamRepositoryMockRecorder struct {
	mock *MockStreamRepository
}

// NewMockStreamRepository creates a new mock instance.
func NewMockStreamRepository(ctrl *gomock.Controller) *MockStreamRepository {
	mock := &MockStreamRepository{ctrl: ctrl}
	mock.recorder = &MockStreamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamRepository) EXPECT() *MockStreamRepositoryMockRecorder {
	return m.recorder
}

// GetStreamById mocks base method.
func (m *MockStreamRepository) GetStreamById(id stream.StreamIdentity) (stream.StreamDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamById", id)
	ret0, _ := ret[0].(stream.StreamDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamById indicates an expected call of GetStreamById.
func (mr *MockStreamRepositoryMockRecorder) GetStreamById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamById", reflect.TypeOf((*MockStreamRepository)(nil).GetStreamById), id)
}

// MockBackfillRequestRepository is a mock of BackfillRequestRepository interface.
type MockBackfillRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBackfillRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockBackfillRequestRepositoryMockRecorder is the mock recorder for MockBackfillRequestRepository.
type MockBackfillRequestRepositoryMockRecorder struct {
	mock *MockBackfillRequestRepository
}

// NewMockBackfillRequestRepository creates a new mock instance.
func NewMockBackfillRequestRepository(ctrl *gomock.Controller) *MockBackfillRequestRepository {
	mock := &MockBackfillRequestRepository{ctrl: ctrl}
	mock.recorder = &MockBackfillRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackfillRequestRepository) EXPECT() *MockBackfillRequestRepositoryMockRecorder {
	return m.recorder
}

// CreateBackfillRequest mocks base method.
func (m *MockBackfillRequestRepository) CreateBackfillRequest(id stream.StreamIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBackfillRequest", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBackfillRequest indicates an expected call of CreateBackfillRequest.
func (mr *MockBackfillRequestRepositoryMockRecorder) CreateBackfillRequest(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBackfillRequest", reflect.TypeOf((*MockBackfillRequestRepository)(nil).CreateBackfillRequest), id)
}
