// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SneaksAndData/arcane-operator/services/controllers/stream_class (interfaces: StreamReconcilerFactory)
//
// Generated by this command:
//
//	mockgen -destination=./tests/mocks/stream_reconciler_factory.go -package=mocks github.com/SneaksAndData/arcane-operator/services/controllers/stream_class StreamReconcilerFactory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	"github.com/SneaksAndData/arcane-operator/services/controllers"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// MockStreamReconcilerFactory is a mock of StreamReconcilerFactory interface.
type MockStreamReconcilerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockStreamReconcilerFactoryMockRecorder
	isgomock struct{}
}

// MockStreamReconcilerFactoryMockRecorder is the mock recorder for MockStreamReconcilerFactory.
type MockStreamReconcilerFactoryMockRecorder struct {
	mock *MockStreamReconcilerFactory
}

// NewMockStreamReconcilerFactory creates a new mock instance.
func NewMockStreamReconcilerFactory(ctrl *gomock.Controller) *MockStreamReconcilerFactory {
	mock := &MockStreamReconcilerFactory{ctrl: ctrl}
	mock.recorder = &MockStreamReconcilerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamReconcilerFactory) EXPECT() *MockStreamReconcilerFactoryMockRecorder {
	return m.recorder
}

// CreateStreamReconciler mocks base method.
func (m *MockStreamReconcilerFactory) CreateStreamReconciler(ctx context.Context, gvk schema.GroupVersionKind) (controllers.StreamReconciler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStreamReconciler", ctx, gvk)
	ret0, _ := ret[0].(controllers.StreamReconciler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStreamReconciler indicates an expected call of CreateStreamReconciler.
func (mr *MockStreamReconcilerFactoryMockRecorder) CreateStreamReconciler(ctx, gvk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStreamReconciler", reflect.TypeOf((*MockStreamReconcilerFactory)(nil).CreateStreamReconciler), ctx, gvk)
}
