// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SneaksAndData/arcane-operator/services/controllers (interfaces: StreamReconciler)
//
// Generated by this command:
//
//	mockgen -destination=./tests/mocks/stream_reconciler.go -package=mocks github.com/SneaksAndData/arcane-operator/services/controllers StreamReconciler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	cache "sigs.k8s.io/controller-runtime/pkg/cache"
	controller "sigs.k8s.io/controller-runtime/pkg/controller"
)

// MockStreamReconciler is a mock of StreamReconciler interface.
type MockStreamReconciler struct {
	ctrl     *gomock.Controller
	recorder *MockStreamReconcilerMockRecorder
	isgomock struct{}
}

// MockStreamReconcilerMockRecorder is the mock recorder for MockStreamReconciler.
type MockStreamReconcilerMockRecorder struct {
	mock *MockStreamReconciler
}

// NewMockStreamReconciler creates a new mock instance.
func NewMockStreamReconciler(ctrl *gomock.Controller) *MockStreamReconciler {
	mock := &MockStreamReconciler{ctrl: ctrl}
	mock.recorder = &MockStreamReconcilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamReconciler) EXPECT() *MockStreamReconcilerMockRecorder {
	return m.recorder
}

// SetupUnmanaged mocks base method.
func (m *MockStreamReconciler) SetupUnmanaged(arg0 cache.Cache) (controller.Controller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupUnmanaged", arg0)
	ret0, _ := ret[0].(controller.Controller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupUnmanaged indicates an expected call of SetupUnmanaged.
func (mr *MockStreamReconcilerMockRecorder) SetupUnmanaged(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupUnmanaged", reflect.TypeOf((*MockStreamReconciler)(nil).SetupUnmanaged), arg0)
}
