// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SneaksAndData/arcane-operator/services/controllers/stream_class (interfaces: StreamControllerFactory,StreamControllerHandle)
//
// Generated by this command:
//
//	mockgen -destination=./tests/mocks/stream_class_mocks.go -package=mocks github.com/SneaksAndData/arcane-operator/services/controllers/stream_class StreamControllerFactory,StreamControllerHandle
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	v1 "github.com/SneaksAndData/arcane-operator/pkg/apis/streaming/v1"
	common "github.com/SneaksAndData/arcane-operator/services/controllers/common"
	stream_class "github.com/SneaksAndData/arcane-operator/services/controllers/stream_class"
	gomock "go.uber.org/mock/gomock"
)

// MockStreamControllerFactory is a mock of StreamControllerFactory interface.
type MockStreamControllerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockStreamControllerFactoryMockRecorder
	isgomock struct{}
}

// MockStreamControllerFactoryMockRecorder is the mock recorder for MockStreamControllerFactory.
type MockStreamControllerFactoryMockRecorder struct {
	mock *MockStreamControllerFactory
}

// NewMockStreamControllerFactory creates a new mock instance.
func NewMockStreamControllerFactory(ctrl *gomock.Controller) *MockStreamControllerFactory {
	mock := &MockStreamControllerFactory{ctrl: ctrl}
	mock.recorder = &MockStreamControllerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamControllerFactory) EXPECT() *MockStreamControllerFactoryMockRecorder {
	return m.recorder
}

// CreateStreamOperator mocks base method.
func (m *MockStreamControllerFactory) CreateStreamOperator(arg0 *v1.StreamClass) (stream_class.StreamControllerHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStreamOperator", arg0)
	ret0, _ := ret[0].(stream_class.StreamControllerHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStreamOperator indicates an expected call of CreateStreamOperator.
func (mr *MockStreamControllerFactoryMockRecorder) CreateStreamOperator(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStreamOperator", reflect.TypeOf((*MockStreamControllerFactory)(nil).CreateStreamOperator), arg0)
}

// MockStreamControllerHandle is a mock of StreamControllerHandle interface.
type MockStreamControllerHandle struct {
	ctrl     *gomock.Controller
	recorder *MockStreamControllerHandleMockRecorder
	isgomock struct{}
}

// MockStreamControllerHandleMockRecorder is the mock recorder for MockStreamControllerHandle.
type MockStreamControllerHandleMockRecorder struct {
	mock *MockStreamControllerHandle
}

// NewMockStreamControllerHandle creates a new mock instance.
func NewMockStreamControllerHandle(ctrl *gomock.Controller) *MockStreamControllerHandle {
	mock := &MockStreamControllerHandle{ctrl: ctrl}
	mock.recorder = &MockStreamControllerHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamControllerHandle) EXPECT() *MockStreamControllerHandleMockRecorder {
	return m.recorder
}

// Id mocks base method.
func (m *MockStreamControllerHandle) Id() common.StreamClassWorkerIdentity {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Id")
	ret0, _ := ret[0].(common.StreamClassWorkerIdentity)
	return ret0
}

// Id indicates an expected call of Id.
func (mr *MockStreamControllerHandleMockRecorder) Id() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Id", reflect.TypeOf((*MockStreamControllerHandle)(nil).Id))
}

// IsUpdateNeeded mocks base method.
func (m *MockStreamControllerHandle) IsUpdateNeeded(obj *v1.StreamClass) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUpdateNeeded", obj)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUpdateNeeded indicates an expected call of IsUpdateNeeded.
func (mr *MockStreamControllerHandleMockRecorder) IsUpdateNeeded(obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUpdateNeeded", reflect.TypeOf((*MockStreamControllerHandle)(nil).IsUpdateNeeded), obj)
}

// Start mocks base method.
func (m *MockStreamControllerHandle) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockStreamControllerHandleMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockStreamControllerHandle)(nil).Start))
}

// Stop mocks base method.
func (m *MockStreamControllerHandle) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockStreamControllerHandleMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockStreamControllerHandle)(nil).Stop))
}
