// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SneaksAndData/arcane-operator/services/controllers/stream_class (interfaces: UnmanagedControllerFactory)
//
// Generated by this command:
//
//	mockgen -destination=./tests/mocks/unmanaged_controller_factory.go -package=mocks github.com/SneaksAndData/arcane-operator/services/controllers/stream_class UnmanagedControllerFactory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	controller "sigs.k8s.io/controller-runtime/pkg/controller"
)

// MockUnmanagedControllerFactory is a mock of UnmanagedControllerFactory interface.
type MockUnmanagedControllerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockUnmanagedControllerFactoryMockRecorder
	isgomock struct{}
}

// MockUnmanagedControllerFactoryMockRecorder is the mock recorder for MockUnmanagedControllerFactory.
type MockUnmanagedControllerFactoryMockRecorder struct {
	mock *MockUnmanagedControllerFactory
}

// NewMockUnmanagedControllerFactory creates a new mock instance.
func NewMockUnmanagedControllerFactory(ctrl *gomock.Controller) *MockUnmanagedControllerFactory {
	mock := &MockUnmanagedControllerFactory{ctrl: ctrl}
	mock.recorder = &MockUnmanagedControllerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnmanagedControllerFactory) EXPECT() *MockUnmanagedControllerFactoryMockRecorder {
	return m.recorder
}

// CreateStreamController mocks base method.
func (m *MockUnmanagedControllerFactory) CreateStreamController(ctx context.Context, gvk schema.GroupVersionKind) (controller.Controller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStreamController", ctx, gvk)
	ret0, _ := ret[0].(controller.Controller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStreamController indicates an expected call of CreateStreamController.
func (mr *MockUnmanagedControllerFactoryMockRecorder) CreateStreamController(ctx, gvk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStreamController", reflect.TypeOf((*MockUnmanagedControllerFactory)(nil).CreateStreamController), ctx, gvk)
}
