// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SneaksAndData/arcane-operator/services/controllers (interfaces: UnmanagedReconciler)
//
// Generated by this command:
//
//	mockgen -destination=./tests/mocks/unmanaged_reconciler.go -package=mocks github.com/SneaksAndData/arcane-operator/services/controllers UnmanagedReconciler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	meta "k8s.io/apimachinery/pkg/api/meta"
	runtime "k8s.io/apimachinery/pkg/runtime"
	cache "sigs.k8s.io/controller-runtime/pkg/cache"
	controller "sigs.k8s.io/controller-runtime/pkg/controller"
)

// MockUnmanagedReconciler is a mock of UnmanagedReconciler interface.
type MockUnmanagedReconciler struct {
	ctrl     *gomock.Controller
	recorder *MockUnmanagedReconcilerMockRecorder
	isgomock struct{}
}

// MockUnmanagedReconcilerMockRecorder is the mock recorder for MockUnmanagedReconciler.
type MockUnmanagedReconcilerMockRecorder struct {
	mock *MockUnmanagedReconciler
}

// NewMockUnmanagedReconciler creates a new mock instance.
func NewMockUnmanagedReconciler(ctrl *gomock.Controller) *MockUnmanagedReconciler {
	mock := &MockUnmanagedReconciler{ctrl: ctrl}
	mock.recorder = &MockUnmanagedReconcilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnmanagedReconciler) EXPECT() *MockUnmanagedReconcilerMockRecorder {
	return m.recorder
}

// SetupUnmanaged mocks base method.
func (m *MockUnmanagedReconciler) SetupUnmanaged(arg0 cache.Cache, scheme *runtime.Scheme, mapper meta.RESTMapper) (controller.Controller, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupUnmanaged", arg0, scheme, mapper)
	ret0, _ := ret[0].(controller.Controller)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupUnmanaged indicates an expected call of SetupUnmanaged.
func (mr *MockUnmanagedReconcilerMockRecorder) SetupUnmanaged(arg0, scheme, mapper any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupUnmanaged", reflect.TypeOf((*MockUnmanagedReconciler)(nil).SetupUnmanaged), arg0, scheme, mapper)
}
