//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024-2026 ECCO Data & AI Open-Source Project Maintainers.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronJobBackend) DeepCopyInto(out *CronJobBackend) {
	*out = *in
	out.JobTemplateRef = in.JobTemplateRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobBackend.
func (in *CronJobBackend) DeepCopy() *CronJobBackend {
	if in == nil {
		return nil
	}
	out := new(CronJobBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionSettings) DeepCopyInto(out *ExecutionSettings) {
	*out = *in
	out.BackfillJobTemplateRef = in.BackfillJobTemplateRef
	in.StreamingBackend.DeepCopyInto(&out.StreamingBackend)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionSettings.
func (in *ExecutionSettings) DeepCopy() *ExecutionSettings {
	if in == nil {
		return nil
	}
	out := new(ExecutionSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockStreamDefinition) DeepCopyInto(out *MockStreamDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockStreamDefinition.
func (in *MockStreamDefinition) DeepCopy() *MockStreamDefinition {
	if in == nil {
		return nil
	}
	out := new(MockStreamDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MockStreamDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockStreamDefinitionList) DeepCopyInto(out *MockStreamDefinitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MockStreamDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockStreamDefinitionList.
func (in *MockStreamDefinitionList) DeepCopy() *MockStreamDefinitionList {
	if in == nil {
		return nil
	}
	out := new(MockStreamDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MockStreamDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockStreamDefinitionSpec) DeepCopyInto(out *MockStreamDefinitionSpec) {
	*out = *in
	in.ExecutionSettings.DeepCopyInto(&out.ExecutionSettings)
	out.SecretRef = in.SecretRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockStreamDefinitionSpec.
func (in *MockStreamDefinitionSpec) DeepCopy() *MockStreamDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(MockStreamDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MockStreamDefinitionStatus) DeepCopyInto(out *MockStreamDefinitionStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MockStreamDefinitionStatus.
func (in *MockStreamDefinitionStatus) DeepCopy() *MockStreamDefinitionStatus {
	if in == nil {
		return nil
	}
	out := new(MockStreamDefinitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchJobBackend) DeepCopyInto(out *BatchJobBackend) {
	*out = *in
	out.JobTemplateRef = in.JobTemplateRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchJobBackend.
func (in *BatchJobBackend) DeepCopy() *BatchJobBackend {
	if in == nil {
		return nil
	}
	out := new(BatchJobBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamingBackend) DeepCopyInto(out *StreamingBackend) {
	*out = *in
	if in.BatchJobBackend != nil {
		in, out := &in.BatchJobBackend, &out.BatchJobBackend
		*out = new(BatchJobBackend)
		**out = **in
	}
	if in.CronJobBackend != nil {
		in, out := &in.CronJobBackend, &out.CronJobBackend
		*out = new(CronJobBackend)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamingBackend.
func (in *StreamingBackend) DeepCopy() *StreamingBackend {
	if in == nil {
		return nil
	}
	out := new(StreamingBackend)
	in.DeepCopyInto(out)
	return out
}
