// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SneaksAndData/arcane-operator/services/job (interfaces: SecretReferenceProvider)
//
// Generated by this command:
//
//	mockgen -destination=./tests/mocks/secret_reference_provider.go -package=mocks github.com/SneaksAndData/arcane-operator/services/job SecretReferenceProvider
//

// Package mocks is a generated GoMock package.
package job_mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockSecretReferenceProvider is a mock of SecretReferenceProvider interface.
type MockSecretReferenceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSecretReferenceProviderMockRecorder
	isgomock struct{}
}

// MockSecretReferenceProviderMockRecorder is the mock recorder for MockSecretReferenceProvider.
type MockSecretReferenceProviderMockRecorder struct {
	mock *MockSecretReferenceProvider
}

// NewMockSecretReferenceProvider creates a new mock instance.
func NewMockSecretReferenceProvider(ctrl *gomock.Controller) *MockSecretReferenceProvider {
	mock := &MockSecretReferenceProvider{ctrl: ctrl}
	mock.recorder = &MockSecretReferenceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretReferenceProvider) EXPECT() *MockSecretReferenceProviderMockRecorder {
	return m.recorder
}

// GetReferenceForSecret mocks base method.
func (m *MockSecretReferenceProvider) GetReferenceForSecret(name string) (*v1.LocalObjectReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReferenceForSecret", name)
	ret0, _ := ret[0].(*v1.LocalObjectReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReferenceForSecret indicates an expected call of GetReferenceForSecret.
func (mr *MockSecretReferenceProviderMockRecorder) GetReferenceForSecret(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReferenceForSecret", reflect.TypeOf((*MockSecretReferenceProvider)(nil).GetReferenceForSecret), name)
}
