{{- if .Values.rbac.clusterRole.streamClassViewer.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.clusteRole.streamClassViewer" . }}
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    {{- include "app.labels" $ | nindent 4 }}
    {{- with .Values.rbac.clusterRole.streamClassViewer.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.rbac.clusterRole.streamClassViewer.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - streaming.sneaksanddata.com
    resources:
      - stream-classes
{{- end }}
