{{- if .Values.rbac.clusterRole.jobEditor.create-}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.clusteRole.jobEditor" . }}
rules:
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - batch
    resources:
      - jobs
{{- end }}
