{{- if .Values.rbac.clusterRole.jobViewer.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.clusteRole.jobViewer" . }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    {{- with .Values.rbac.clusterRole.jobViewer.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.rbac.clusterRole.jobViewer.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - batch
    resources:
      - jobs
{{- end }}
