{{- if .Values.rbac.clusterRole.create-}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-job-manager
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - verbs:
      - get
      - list
      - create
      - delete
      - deletecollection
      - patch
      - update
    apiGroups:
      - batch
    resources:
      - jobs
{{- end }}
