{{- if .Values.rbac.clusterRole.jobTemplateEditor.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.clusteRole.jobTemplateEditor" . }}
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - verbs:
      - create
      - update
      - patch
      - delete
    apiGroups:
      - streaming.sneaksanddata.com
    resources:
      - streaming-job-templates
{{- end }}
