{{- if .Values.rbac.clusterRole.streamClassViewer -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.clusteRole.streamClassViewer" }}
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - streaming.sneaksanddata.com
    resources:
      - stream-classes
{{- end }}
