apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {
      "StreamingJobOperatorServiceConfiguration": {
        "MaxBufferCapacity": {{ .Values.settings.jobMaintenanceController.maxEventBufferCapacity }},
        "Namespace": "{{ default .Release.Namespace .Values.settings.jobMaintenanceController.jobNamespace }}"
      },
      "StreamClassOperatorServiceConfiguration": {
        "Namespace": "{{ default .Release.Namespace .Values.settings.streamClassController.streamClassesNamespace }}",
        "MaxBufferCapacity": 100,
        "ApiGroup": "streaming.sneaksanddata.com",
        "Version": "v1beta1",
        "Plural": "stream-classes"
      },
      "StreamingJobTemplateRepositoryConfiguration": {
        "ResourceConfiguration": {
          "ApiGroup": "streaming.sneaksanddata.com",
          "Version": "v1",
          "Plural": "streaming-job-templates"
        }
      },
      "MetricsReporterConfiguration": {
        "MetricsPublisherActorConfiguration": {
          "UpdateInterval": "00:00:10",
          "InitialDelay": "00:00:10"
        }
      },
      "LoggerConfiguration": {
        "CustomProperties": {{ .Values.settings.customLoggingProperties | toJson }}
      }
    }
    
