{{- if .Values.customResourceDefinitions.create }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: streaming-job-templates.streaming.sneaksanddata.com
spec:
  group: streaming.sneaksanddata.com
  scope: Namespaced
  names:
    plural: streaming-job-templates
    singular: streaming-job-template
    kind: StreamingJobTemplate
    shortNames:
      - sjt
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                metadata:
                  type: object
                  properties:
                    labels:
                      type: object
                      additionalProperties:
                        type: string
                      nullable: true
                    annotations:
                      type: object
                      additionalProperties:
                        type: string
                      nullable: true
                  description: Job metadata
                template:
                  type: object
                  x-kubernetes-embedded-resource: true
                  x-kubernetes-preserve-unknown-fields: true
{{- end }}
