{{- if .Values.garbageCollector.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.name" . }}-garbage-collector
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    app.kubernetes.io/component: garbage-collector
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.garbageCollector.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.garbageCollector.successfulJobsHistoryLimit | default 3 }}
  failedJobsHistoryLimit: {{ .Values.garbageCollector.failedJobsHistoryLimit | default 1 }}
  jobTemplate:
    metadata:
      labels:
        {{- include "app.labels" $ | nindent 8 }}
        app.kubernetes.io/component: garbage-collector
      {{- with .Values.additionalAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      backoffLimit: {{ .Values.garbageCollector.backoffLimit | default 3 }}
      template:
        metadata:
          labels:
            {{- include "app.labels" $ | nindent 12 }}
            app.kubernetes.io/component: garbage-collector
          {{- with .Values.additionalAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "app.serviceAccountName" . }}
          restartPolicy: {{ .Values.garbageCollector.restartPolicy | default "OnFailure" }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: garbage-collector
            {{- with .Values.securityContext }}
            securityContext:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            image: "{{ include "app.garbageCollectorImage" . }}"
            imagePullPolicy: "{{ .Values.garbageCollector.image.pullPolicy }}"
            command:
              - /app/arcane-operator
              - garbage-collect
            {{- with .Values.garbageCollector.args }}
            args:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            env:
              - name: ASPNETCORE_ENVIRONMENT
                value: {{ .Values.environment }}
              - name: APPLICATION_VERSION
                value: "{{ (default (printf "v%s" .Chart.AppVersion) .Values.garbageCollector.image.tag) }}"
              - name: ARCANE_OPERATOR__TELEMETRY__CLUSTER_NAME
                value: {{ .Values.settings.telemetry.clusterName | default  "arcane-cluster"}}
              - name: ARCANE_OPERATOR__TELEMETRY__LOG_LEVEL
                value: {{ .Values.settings.telemetry.logLevel | default  "info"}}
          {{- if .Values.datadog.enabled }}
              - name: DATADOG__API_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.datadog.apiKeySecret | quote }}
                    key: {{ .Values.datadog.apiKeySecretKey | quote }}
              - name: DATADOG__ENDPOINT
                value: {{ .Values.datadog.endpoint | quote }}
              - name: DATADOG__APPLICATION_HOST
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
            {{- if .Values.datadog.enableOriginDetection }}
              - name: DD_ENTITY_ID
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.uid
            {{- end }}
            {{- if .Values.datadog.tracer.enabled }}
              - name: DD_INSTRUMENTATION_TELEMETRY_ENABLED
                value: {{ not .Values.datadog.tracer.disable_vendor_telemetry | quote }}
              - name: DD_TRACE_ENABLED
                value: {{ .Values.datadog.tracer.enabled | quote }}
              - name: DD_TRACE_AGENT_URL
                value: {{ .Values.datadog.tracer.agent_url | quote }}
              - name: DD_ENV
                value: {{ .Values.datadog.tracer.service_env | quote }}
            {{- end }}
              - name: DATADOG__SERVICE_NAME
                value: {{ .Values.datadog.serviceName }}
              - name: DD_SERVICE
                value: {{ .Values.datadog.serviceName }}
              - name: DD_VERSION
                value: "{{ (default (printf "v%s" .Chart.AppVersion) .Values.garbageCollector.image.tag) }}"
              - name: DD_DOGSTATSD_URL
                value: {{ .Values.datadog.statsdUrl | quote }}
          {{- end }}
              {{- with .Values.extraEnv }}
                {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- if .Values.extraEnvFrom }}
            envFrom:
              {{- with .Values.extraEnvFrom }}
                {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- end }}
            volumeMounts:
              {{- with .Values.extraVolumeMounts }}
                {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- with .Values.garbageCollector.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          volumes:
              {{- with .Values.extraVolumes }}
                {{- toYaml . | nindent 12 }}
              {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}

